#!/command/with-contenv bash

if [ -z "${SSH_PASSWORD:-}" ]; then
  echo "SSH_PASSWORD is null, Use default password"
  SSH_PASSWORD="mfy@2025"
fi

echo "INFO: Change user password to $SSH_PASSWORD"
echo "root:$SSH_PASSWORD" | sudo chpasswd
echo "$NB_USER:$SSH_PASSWORD" | sudo chpasswd